name: quickbms-lsp

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly-2021-01-27
          default: true
          components: rustfmt
      - name: Install tree-sitter
        run: cd tree-sitter-quickbms && npm install --save-dev tree-sitter-cli
      - name: Install pytest
        run: pip install pytest
      - name: Construct parser
        run: make grammar
      - name: Test grammar
        run: make test-grammar
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run regression tests
        run: make regression-test
